### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by protoss1010** [ximsfei/Android-skin-support#105]
佈局中有使用android.support.design.widget.TextInputLayout
只要在Applicataion初始化中設定了
SkinCompatManager.withoutActivity(this)
    .addInflater(new SkinMaterialViewInflater())
    .loadSkin();

就會Crash 如下
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: xxx.xxx.xxx, PID: 22420
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx./xxx.LoginActivity}: android.view.InflateException: Binary XML file line #65: Binary XML file line #65: Error inflating class android.support.design.widget.TextInputLayout
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2725)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2786)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:173)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6459)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
                                                                          Caused by: android.view.InflateException: Binary XML file line #65: Binary XML file line #65: Error inflating class android.support.design.widget.TextInputLayout
                                                                          Caused by: android.view.InflateException: Binary XML file line #65: Error inflating class android.support.design.widget.TextInputLayout
                                                                          Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                             at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:192)
                                                                             at android.content.res.Resources.getColor(Resources.java:939)
                                                                             at android.content.res.Resources.getColor(Resources.java:915)
                                                                             at skin.support.design.widget.SkinMaterialTextInputLayout.<init>(SkinMaterialTextInputLayout.java:57)
                                                                             at skin.support.design.widget.SkinMaterialTextInputLayout.<init>(SkinMaterialTextInputLayout.java:43)
                                                                             at skin.support.design.app.SkinMaterialViewInflater.createView(SkinMaterialViewInflater.java:37)
                                                                             at skin.support.app.SkinCompatViewInflater.createViewFromInflater(SkinCompatViewInflater.java:210)
                                                                             at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:99)
                                                                             at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
                                                                             at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
                                                                             at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                             at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

**Comment by ximsfei** [comment]
![image](https://user-images.githubusercontent.com/9425734/33420814-f6fc3424-d5ea-11e7-804a-d3ad31bfd79a.png)
fixed: `compile 'skin.support:skin-support-design:1.2.6'`
