### ISSUE TITLE
在应用中打开插件程序，会被换肤影响到导致崩溃

### ISSUE THREAD

**Issue by dengyuhan** [ximsfei/Android-skin-support#146]
我用了RePlugin，当我加载插件的时候，抛出下面的异常
插件程序是用了toolbar的，只要不使用`Android-skin-support`就正常
```
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.Toolbar
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 5 to dimension: type=0x3
    at android.content.res.TypedArray.getDimensionPixelOffset(TypedArray.java:672)
    at android.support.v7.widget.TintTypedArray.getDimensionPixelOffset(TintTypedArray.java:188)
    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:278)
    at skin.support.widget.SkinCompatToolbar.<init>(SkinCompatToolbar.java:34)
    at skin.support.widget.SkinCompatToolbar.<init>(SkinCompatToolbar.java:30)
    at skin.support.app.SkinCompatViewInflater.createViewFromV7(SkinCompatViewInflater.java:201)
    at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:95)
    at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
    at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
    at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
    at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:406)
    at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at android.app.Activity.performCreate(Activity.java:6751)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2768)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:160)
    at android.app.ActivityThread.main(ActivityThread.java:6252)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
```

这是我主程序初始化的代码
```
SkinCompatManager.withoutActivity(mApplication)
                .setSkinStatusBarColorEnable(true)
                .setSkinWindowBackgroundEnable(false)
                .loadSkin();
```

**Comment by ximsfei** [comment]
尝试一下这个方法
`SkinCompatManager.java `

```
    /**
     * 设置是否所有Activity都换肤.
     *
     * @param enable true: 所有Activity都换肤; false: 添加注解Skinable或实现SkinCompatSupportable的Activity支持换肤.
     * @return
     */
    public SkinCompatManager setSkinAllActivityEnable(boolean enable) {
        mSkinAllActivityEnable = enable;
        return this;
    }
```

**Comment by yaochangliang159** [comment]
@ximsfei 
作者你好，我刚打开APP，正常进入一个界面，突然报错了，我一看日志，好像和这个库有关，平常都是好着的啊，，怎么偶尔来这么一下，让人心里对这个库有点虚，，错误如下：
` FATAL EXCEPTION: main
                                                                             Process: com.hyphenate.ehetu_teacher, PID: 21311
                                                                             android.view.InflateException: Binary XML file line #17: Error inflating class ImageView
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                                 at android.support.v7.widget.ActionBarContextView.initForMode(ActionBarContextView.java:162)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionModeFromWindow(AppCompatDelegateImplV9.java:831)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionMode(AppCompatDelegateImplV9.java:712)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:291)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:274)
                                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java)
                                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.ViewGroup.startActionModeForChild(ViewGroup.java)
                                                                                 at android.view.View.startActionMode(View.java)
                                                                                 at android.widget.Editor.startSelectionActionMode(Editor.java)
                                                                                 at android.widget.Editor.performLongClick(Editor.java)
                                                                                 at android.widget.TextView.performLongClick(TextView.java)
                                                                                 at android.view.View$CheckForLongPress.run(View.java)
                                                                                 at android.os.Handler.handleCallback(Handler.java)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java)
                                                                                 at android.os.Looper.loop(Looper.java)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                                 at android.content.res.Resources.loadDrawable(Resources.java)
                                                                                 at android.content.res.Resources.getDrawable(Resources.java)
                                                                                 at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
                                                                                 at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
                                                                                 at skin.support.content.res.SkinCompatResources.getSkinDrawable(SkinCompatResources.java:146)
                                                                                 at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:160)
                                                                                 at skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:198)
                                                                                 at skin.support.widget.SkinCompatImageHelper.applySkin(SkinCompatImageHelper.java:46)
                                                                                 at skin.support.widget.SkinCompatImageHelper.loadFromAttributes(SkinCompatImageHelper.java:35)
                                                                                 at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:30)
                                                                                 at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:21)
                                                                                 at skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:149)
                                                                                 at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
                                                                                 at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
                                                                                 at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
                                                                                 at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                             	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInfl`

**Comment by pudao2010** [comment]
是否验证了RePlugin部分是不能换肤的？我测试了好像不能生效
