### ISSUE TITLE
SkinCompatResources加载SVG资源报Resources$NotFoundException， 使用的2.2.3版本

### ISSUE THREAD

**Issue by SjAnd** [ximsfei/Android-skin-support#149]
05-15 03:10:50.792 11520-11520/com.wondertek.paper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wondertek.paper, PID: 11520
    android.view.InflateException: Binary XML file line #17: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.support.v7.widget.ActionBarContextView.initForMode(ActionBarContextView.java:162)
        at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionModeFromWindow(AppCompatDelegateImplV9.java:826)
        at android.support.v7.app.AppCompatDelegateImplV9.startSupportActionMode(AppCompatDelegateImplV9.java:707)
        at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:292)
        at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:275)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2375)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2362)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
        at android.view.View.startActionMode(View.java:4536)
        at android.widget.Editor.startSelectionActionMode(Editor.java:1551)
        at android.widget.Editor.performLongClick(Editor.java:859)
        at android.widget.TextView.performLongClick(TextView.java:8362)
        at android.view.View$CheckForLongPress.run(View.java:18401)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:129)
        at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
        at skin.support.b.a.a.i(SkinCompatResources.java:146)
        at skin.support.b.a.a.j(SkinCompatResources.java:160)
        at skin.support.b.a.a.d(SkinCompatResources.java:198)
        at skin.support.widget.f.a(SkinCompatImageHelper.java:46)
        at skin.support.widget.f.a(SkinCompatImageHelper.java:35)
    	at skin.support.widget.SkinCompatImageView.<init>(SkinCom

**Comment by ximsfei** [comment]
demo application中最后一行开关开一下。
`AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);`

**Comment by SjAnd** [comment]
我开了之后是好的，但是我奇怪为什么使用原生的是ok的？

**Comment by SjAnd** [comment]
好的 了解了，非常感谢
