### ISSUE TITLE
’ java.lang.ref.Reference.get()' on a null object reference

### ISSUE THREAD

**Issue by donnyzhou** [ximsfei/Android-skin-support#151]
从Android Studio运行到手机上，报错
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                       at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkin(SkinActivityLifecycle.java:184)

这里的代码是这样的：
        public void updateSkin(SkinObservable observable, Object o) {
            // 当前Activity，或者非Activity，立即刷新，否则延迟到下次onResume方法中刷新。
            if (mContext == mCurActivityRef.get()
                    || !(mContext instanceof Activity)) {
只有从Android Studio运行到手机，打开Welcome页面的时候闪退，再次打开app不再报错。怎么解决，麻烦给点建议。

**Comment by guanxionghuai** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
        at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkin(SkinActivityLifecycle.java:184)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:40)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:29)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:404)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:357)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)



我也发现了这个问题

**Comment by mr-wind** [comment]
同样遇到了这个问题

**Comment by ximsfei** [comment]
3.1.0-beta1已经修复啦

**Comment by donnyzhou** [comment]
使用3.1.0-beta1不再报错了，非常感谢！
