### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by uncleleonfan** [ximsfei/Android-skin-support#157]
代码中使用了MVVM框架，使用skin之后出现异常：
    java.lang.ExceptionInInitializerError
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:289)
        at skin.support.app.SkinCompatViewInflater.createViewFromTag(SkinCompatViewInflater.java:238)
        at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:103)
        at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
        at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116)
        at com.hotlink.loois.trade.databinding.SellListItemBinding.inflate(SellListItemBinding.java:100)
        at com.hotlink.loois.trade.databinding.SellListItemBinding.inflate(SellListItemBinding.java:96)

异常出现在使用创建Binding过程中：
    @Override
    public View onCreateItemView(ViewGroup viewGroup) {
        LayoutInflater inflater = LayoutInflater.from(getContext());
        SellListItemBinding binding = SellListItemBinding.inflate(inflater, viewGroup, false);//这一句抛异常
        return binding.getRoot();
    }

**Comment by ximsfei** [comment]
3.1.0-beta1？
布局文件内容？

**Comment by ximsfei** [comment]
emmm. 你的日志截图不全哈.
`private static int SELL_COLOR = Color.parseColor("e5bf164a");`
这行代码有问题。
`private static int SELL_COLOR = Color.parseColor("#e5bf164a");`
颜色值必须是#开始的，或者特殊的单词。

**Comment by uncleleonfan** [comment]
确实是的，日志就看到那么多，所以没定位到这里来。非常感谢！
