### ISSUE TITLE
TabLayout 使用 tabBackground 夜间模式没生效

### ISSUE THREAD

**Issue by ImportEffort** [ximsfei/Android-skin-support#164]
应用使用 插件化换肤

```
<android.support.design.widget.TabLayout
            android:id="@+id/innerTabLayout"
            android:layout_width="128dp"
            android:layout_height="27dp"
            android:layout_centerInParent="true"
            android:layout_centerVertical="true"
            app:tabBackground="@drawable/tab_mystock_top_selector"
            app:tabGravity="center"
            app:tabIndicatorHeight="0dp"
            app:tabSelectedTextColor="@color/white"
            app:tabTextColor="@color/tablayout_text_unselect">

            <android.support.design.widget.TabItem
                android:layout_width="64dp"
                android:layout_height="match_parent"
                android:text="自选"/>

            <android.support.design.widget.TabItem
                android:layout_width="64dp"
                android:layout_height="match_parent"
                android:text="市场"/>

        </android.support.design.widget.TabLayout>
```
tab_mystock_top_selector （同时放在日间夜间资源包中）如下

```
<selector xmlns:android="http://schemas.android.com/apk/res/android" >

	<item android:drawable="@drawable/shape_rect_red_seleted" android:state_selected="true" />
	<item android:drawable="@drawable/shape_rect_red" />

</selector>
```
shape_rect_red_seleted （同时放在日间夜间资源包中）

```
<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <solid android:color="@color/tablayout_tab_unselect" />

</shape>
```
日间
`  <color name="tablayout_tab_unselect">#EC5A58</color>`
夜间
` <color name="tablayout_tab_unselect">#1f222d</color>`

代码运行后，切换日间夜间，tab的背景没有换。

**Comment by ximsfei** [comment]
TabLayout的app:tabBackground默认没做换肤支持，需要自己扩展

**Comment by ImportEffort** [comment]
可以指点下，扩展思路是什么么？

**Comment by ximsfei** [comment]
参照自定义View换肤实现

**Comment by ImportEffort** [comment]
不考虑默认支持一下么？ 毕竟系统控件应用率还是蛮高的

**Comment by ImportEffort** [comment]
昨天尝试了自定义View换肤实现：
```
    <####.ui.component.segment.SegmentedTab
            android:id="@+id/innerTabLayout"
            android:layout_width="128dp"
            android:layout_height="27dp"
            android:layout_centerInParent="true"
            android:layout_centerVertical="true"
            app:borderColorSelected="@color/tablayout_tab_select"
            app:borderColorUnselected="@color/tablayout_tab_unselect"
            app:tabSelectedColor="@color/tablayout_tab_select"
            app:tabUnselectedColor="@color/segment_tab_unselected"
            app:tabTextColor ="@color/tablayout_text_select"
            app:tabTextUnSelectedColor ="@color/tablayout_text_unselect"
            app:titleTextSize="14sp"/>
```
其中下面两个属性决定内部tab的颜色
```
 app:tabTextColor ="@color/tablayout_text_select"
 app:tabTextUnSelectedColor ="@color/tablayout_text_unselect"
```
tablayout_text_select 和 tablayout_text_unselect
```
//skin 包中
    <color name="tablayout_text_unselect">#acbad0</color>
    <color name="tablayout_text_select">#ffffff</color>

// 非Skin包中
 <color name="tablayout_text_unselect">#EC5A58</color>
  <color name="tablayout_text_select">#FFFFFF</color>
```

SegmentTab 内部 applySkin部分为
```
  private void applyColor() {
        mBorderColorResId = SkinCompatHelper.checkResourceId(mBorderColorResId);
        if (mBorderColorResId != 0) {
            borderColorSelected = SkinCompatResources.getColor(getContext(), mBorderColorResId);

        }

        mBorderUnColorResId = SkinCompatHelper.checkResourceId(mBorderUnColorResId);
        if (mBorderUnColorResId != 0) {
            borderColorUnselected = SkinCompatResources.getColor(getContext(), mBorderUnColorResId);

        }
        mTabColorResId = SkinCompatHelper.checkResourceId(mTabColorResId);
        if (mTabColorResId != 0) {
            tabSelectedColor = SkinCompatResources.getColor(getContext(), mTabColorResId);
        }

        mTabUnColorResId = SkinCompatHelper.checkResourceId(mTabUnColorResId);
        LogUtils.e("mTabUnColorResId  " + titleTextColor);

        if (mTabUnColorResId != 0) {
            tabUnselectedColor = SkinCompatResources.getColor(getContext(), mTabUnColorResId);
        }

        titleTextColor = SkinCompatHelper.checkResourceId(titleTextColor);

        LogUtils.e("titleTextColor  " + titleTextColor);

        if (titleTextColor != SkinCompatHelper.INVALID_ID) {
            titleTextColor = SkinCompatResources.getColor(getContext(), titleTextColor);
        }
        titleTextUnSelectedColor = SkinCompatHelper.checkResourceId(titleTextUnSelectedColor);
        LogUtils.e("titleUnSelectedColor  " + titleTextUnSelectedColor);

        if (titleTextUnSelectedColor != SkinCompatHelper.INVALID_ID ) {
            titleTextUnSelectedColor = SkinCompatResources.getColor(getContext(), titleTextUnSelectedColor);
        }

        for (int i = 0; i < tabViewSparseArray.size(); i++) {
            TabView tabView = tabViewSparseArray.valueAt(i);
            tabView.setBackground(this.tabSelectedColor, this.tabUnselectedColor, this.borderColorSelected, this.borderColorUnselected);
            tabView.setTextColor(titleTextColor,titleTextUnSelectedColor);
        }

    }
````
tabView.setBackground 方法实现为
```
    public void setBackground(int colorSelected, int colorUnselected, int colorBorderSelected, int colorBorderUnselected) {
        StateListDrawable drawableStates = getDrawableStates(colorSelected, colorUnselected, colorBorderSelected, colorBorderUnselected);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
            this.view.setBackgroundDrawable(drawableStates);
        } else {
            this.view.setBackground(drawableStates);
        }
    }

    private StateListDrawable getDrawableStates(int colorSelected, int colorUnselected, int colorBorderSelected, int colorBorderUnselected) {
        StateListDrawable stateListDrawable = new StateListDrawable();
        stateListDrawable.addState(new int[]{android.R.attr.state_pressed}, getDrawable(colorSelected, colorBorderSelected));
        stateListDrawable.addState(new int[]{android.R.attr.state_focused}, getDrawable(colorSelected, colorBorderSelected));
        stateListDrawable.addState(new int[]{android.R.attr.state_selected}, getDrawable(colorSelected, colorBorderSelected));
        stateListDrawable.addState(new int[]{}, getDrawable(colorUnselected, colorBorderUnselected));

        return stateListDrawable;
    }
```

tabView.setTextColor 方法实现为
```
    /**
     *
     * @param selected 点击效果
     * @param normal 正常效果
     * @return
     */
    private ColorStateList createColorStateList(int selected, int normal) {
        int[] colors = new int[]{selected, normal};
        int[][] states = new int[2][];
        states[0] = new int[]{android.R.attr.state_selected};
        states[1] = new int[]{};
        return new ColorStateList(states, colors);
    }


    public void setTextColor(int colorSelected, int colorUnselected) {
        txtTitle.setTextColor(createColorStateList(colorSelected,colorUnselected));
    }
```
当在页面内点击切换夜间模式后会报错：

````
E/ExceptionHandler: android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getResourceTypeName(ResourcesImpl.java:333)
        at android.content.res.Resources.getResourceTypeName(Resources.java:2115)
        at skin.support.content.res.SkinCompatUserThemeManager.getEntryName(SkinCompatUserThemeManager.java:383)
        at skin.support.content.res.SkinCompatUserThemeManager.getColorStateList(SkinCompatUserThemeManager.java:180)
        at skin.support.content.res.SkinCompatResources.getSkinColor(SkinCompatResources.java:113)
        at skin.support.content.res.SkinCompatResources.getColor(SkinCompatResources.java:240)
        at com.niuguwang.stock.ui.component.segment.SegmentedTab.applyColor(SegmentedTab.java:256)
        at com.niuguwang.stock.ui.component.segment.SegmentedTab.applySkin(SegmentedTab.java:224)
        at skin.support.app.SkinCompatDelegate.applySkin(SkinCompatDelegate.java:101)
        at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkinForce(SkinActivityLifecycle.java:206)
        at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkin(SkinActivityLifecycle.java:186)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:40)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:29)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:404)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:357)
        at android.os.AsyncTask.finish(AsyncTask.java:727)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
````
只有对tabView设置颜色属性的会报错，同样设置的setBackground 方法就没有爆颜色找不到的错误，当App重启后，也能正确的应用所设置的夜间模式的值。在页面不重启的情况下就会报错。请问这是什么原因呢？
