### ISSUE TITLE
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2

### ISSUE THREAD

**Issue by jhwsx** [ximsfei/Android-skin-support#181]
Hi,

When I wanted to add daynight mode into my app, I finally selected Android-skin-support, for it's loose-coupling with my code, which is better than other the same types libs.

However, after I integrate Android-skin-support into my app, this bug happened online on specified phone model. The users feebacked the bug to me. I promised to try my best to solve it.

The lib version is 3.1.0-beta1

compileSdkVersion = 26

buildToolsVersion = '26.0.2'

supportLibraryVersion = '26.1.0'

gradle:4.1

'com.android.tools.build:gradle:3.0.0'

The phone is OPPOA31 4.4.4

The crash log is:

`android.view.InflateException: Binary XML file line #24: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.widget.OppoCursorController$FloatPanelViewController.<init>(OppoCursorController.java:1289)
	at android.widget.OppoCursorController.createFloatPanelViewController(OppoCursorController.java:122)
	at android.widget.OppoCursorController$InsertionPointCursorController.<init>(OppoCursorController.java:197)
	at android.widget.OppoCursorController.create(OppoCursorController.java:75)
	at android.widget.OppoEditor.getOppoInsertionController(OppoEditor.java:399)
	at android.widget.OppoEditor.onFocusChanged(OppoEditor.java:286)
	at android.widget.TextView.onFocusChanged(TextView.java:7829)
	at android.view.View.handleFocusGainInternal(View.java:4617)
	at android.view.View.requestFocusNoSearch(View.java:6999)
	at android.view.View.requestFocus(View.java:6978)
	at android.widget.ScrollView.onRequestFocusInDescendants(ScrollView.java:1474)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.View.requestFocus(View.java:6945)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5718)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.widget.TextView.<init>(TextView.java:686)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at skin.support.widget.SkinCompatTextView.<init>(Unknown Source)
	at skin.support.widget.SkinCompatTextView.<init>(Unknown Source)
	at skin.support.app.SkinCompatViewInflater.c(Unknown Source)
	at skin.support.app.SkinCompatViewInflater.a(Unknown Source)
	at skin.support.app.SkinCompatDelegate.a(Unknown Source)
	at skin.support.app.SkinCompatDelegate.onCreateView(Unknown Source)
	at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(Unknown Source)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 53 more
java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.widget.TextView.<init>(TextView.java:686)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at skin.support.widget.SkinCompatTextView.<init>(Unknown Source)
	at skin.support.widget.SkinCompatTextView.<init>(Unknown Source)
	at skin.support.app.SkinCompatViewInflater.c(Unknown Source)
	at skin.support.app.SkinCompatViewInflater.a(Unknown Source)
	at skin.support.app.SkinCompatDelegate.a(Unknown Source)
	at skin.support.app.SkinCompatDelegate.onCreateView(Unknown Source)
	at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(Unknown Source)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.widget.OppoCursorController$FloatPanelViewController.<init>(OppoCursorController.java:1289)
	at android.widget.OppoCursorController.createFloatPanelViewController(OppoCursorController.java:122)
	at android.widget.OppoCursorController$InsertionPointCursorController.<init>(OppoCursorController.java:197)
	at android.widget.OppoCursorController.create(OppoCursorController.java:75)
	at android.widget.OppoEditor.getOppoInsertionController(OppoEditor.java:399)
	at android.widget.OppoEditor.onFocusChanged(OppoEditor.java:286)
	at android.widget.TextView.onFocusChanged(TextView.java:7829)
	at android.view.View.handleFocusGainInternal(View.java:4617)
	at android.view.View.requestFocusNoSearch(View.java:6999)
	at android.view.View.requestFocus(View.java:6978)
	at android.widget.ScrollView.onRequestFocusInDescendants(ScrollView.java:1474)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.View.requestFocus(View.java:6945)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5718)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)`

I find an OPPOR11 6.0 phone in order to recreate this bug, but it's ok. However, I am not able to find the same model phone.

According to the crash log, it may result from the library is not compatible to the OPPO api. That's very bad. And I don't find any line of the log related to my code.

I want to fix this bug asap and better this fabulous skin framework. Could you please help me out?

**Comment by ximsfei** [comment]
I am sorry to reply now. Working during the day is too busy. I tried to fix this bug, and you can upgrade lib version to `3.1.0-beta2`, maybe this problem will not happen again.

**Comment by jhwsx** [comment]
Got it! You're really very helpful.

I'll publish a fix-bug package and send the feedback to you asap.

**Comment by jhwsx** [comment]
Well, I'm sorry to tell you that our approach of trying to fix this bug does not work.

I have received the latest crash log from the kind user, which is caught by CrashHandler:

`TIME=1464717189000
FINGERPRINT=OPPO/A31/A31t:4.4.4/KTU84P/1391528547:user/release-keys
HARDWARE=qcom
UNKNOWN=unknown
RADIO=unknown
BOARD=msm8916
versionCode=7
PRODUCT=A31
versionName=1.2.3.2
DISPLAY=A31_11_160601
USER=root
HOST=ubuntu-121-114
DEVICE=A31
TAGS=release-keys
MODEL=A31
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=KTU84P
ROM_DIFF_VERSION=ColorOS2.0.1
SERIAL=fae6cceb
MANUFACTURER=OPPO
BRAND=OPPO
TYPE=user
android.view.InflateException: Binary XML file line #24: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.widget.OppoCursorController$FloatPanelViewController.<init>(OppoCursorController.java:1289)
	at android.widget.OppoCursorController.createFloatPanelViewController(OppoCursorController.java:122)
	at android.widget.OppoCursorController$InsertionPointCursorController.<init>(OppoCursorController.java:197)
	at android.widget.OppoCursorController.create(OppoCursorController.java:75)
	at android.widget.OppoEditor.getOppoInsertionController(OppoEditor.java:399)
	at android.widget.OppoEditor.onFocusChanged(OppoEditor.java:286)
	at android.widget.TextView.onFocusChanged(TextView.java:7829)
	at android.view.View.handleFocusGainInternal(View.java:4617)
	at android.view.View.requestFocusNoSearch(View.java:6999)
	at android.view.View.requestFocus(View.java:6978)
	at android.widget.ScrollView.onRequestFocusInDescendants(ScrollView.java:1474)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.View.requestFocus(View.java:6945)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5718)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.widget.TextView.<init>(TextView.java:686)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at android.support.v7.app.AppCompatViewInflater.createTextView(Unknown Source)
	at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 53 more
java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.widget.TextView.<init>(TextView.java:686)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
	at android.support.v7.app.AppCompatViewInflater.createTextView(Unknown Source)
	at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.widget.OppoCursorController$FloatPanelViewController.<init>(OppoCursorController.java:1289)
	at android.widget.OppoCursorController.createFloatPanelViewController(OppoCursorController.java:122)
	at android.widget.OppoCursorController$InsertionPointCursorController.<init>(OppoCursorController.java:197)
	at android.widget.OppoCursorController.create(OppoCursorController.java:75)
	at android.widget.OppoEditor.getOppoInsertionController(OppoEditor.java:399)
	at android.widget.OppoEditor.onFocusChanged(OppoEditor.java:286)
	at android.widget.TextView.onFocusChanged(TextView.java:7829)
	at android.view.View.handleFocusGainInternal(View.java:4617)
	at android.view.View.requestFocusNoSearch(View.java:6999)
	at android.view.View.requestFocus(View.java:6978)
	at android.widget.ScrollView.onRequestFocusInDescendants(ScrollView.java:1474)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2425)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2384)
	at android.view.View.requestFocus(View.java:6945)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5718)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)`

The log is almost the same as before, except that it's not related to the skin lib. That's very weird.

**Comment by ximsfei** [comment]
@jhwsx 
Review the workaround [patch](https://github.com/ximsfei/Android-skin-support/commit/e40ae65eaa7f080c216c0b7db7a869e6c3e9d6fe), I had add a try catch at the entrance of the View creation. After the exception occurs here, the original View creation process will be taken. Unfortunately, it still crashed. And no longer related to Android-skin-support. From the crash log, you can see that oppo also modified this part of the code. Maybe it is a defect of this oppo's model, and you need to feedback this bug to oppo.
You can compare the crash log before and after carefully, they are not the same.
