### ISSUE TITLE
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f020004,是否与skin.support有关呢

### ISSUE THREAD

**Issue by zksyp** [ximsfei/Android-skin-support#201]
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.PluginStubActivitySingleTask4}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class ImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:45)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class ImageView
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class ImageView
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f020004
        at android.content.res.ResourcesImpl.getResourceTypeName(ResourcesImpl.java:258)
        at android.content.res.Resources.getResourceTypeName(Resources.java:1964)
        at skin.support.content.res.SkinCompatUserThemeManager.getEntryName(SkinCompatUserThemeManager.java:383)
        at skin.support.content.res.SkinCompatUserThemeManager.getColorStateList(SkinCompatUserThemeManager.java:180)
        at skin.support.content.res.SkinCompatResources.getSkinDrawable(SkinCompatResources.java:157)
        at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:214)
        at skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
        at skin.support.widget.SkinCompatImageHelper.applySkin(SkinCompatImageHelper.java:55)
        at skin.support.widget.SkinCompatImageHelper.loadFromAttributes(SkinCompatImageHelper.java:35)
        at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:30)
        at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:21)
        at skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:149)
        at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
        at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:58)
        at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:35)
        at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.tencent.wstt.gt.collector.monitor.yhook.ViewBuildHookList.inflate(ViewBuildHookList.java:38)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.tuotuo.solo.plugin.partner.user.login.ActivityMobileLogin.onCreate(ActivityMobileLogin.java:71)
        at android.app.Activity.performCreate(Activity.java:7003)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)

**Comment by ximsfei** [comment]
插件化开发需要自行做适配

**Comment by yqzGitHub** [comment]
插件化开发需要自行做适配

如何适配，能讲下思路吗？
