### ISSUE TITLE
线上crash，4.4版本

### ISSUE THREAD

**Issue by YummyLau** [ximsfei/Android-skin-support#213]
线上出现 
```
   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f08001a
at android.content.res.Resources.loadDrawable(Resources.java:2096)
at android.content.res.Resources.getDrawable(Resources.java:700)
at android.support.v7.widget.ResourcesWrapper.android.graphics.drawable.Drawable getDrawable(int)(Proguard)
    android.graphics.drawable.Drawable getDrawable(int,android.content.res.Resources$Theme)
```
代码定位为
```
 private Drawable getSkinDrawable(Context context, int resId) {
        if (!isDefaultSkin) {
            int targetResId = getTargetResId(context, resId);
            if (targetResId != 0) {
                return mResources.getDrawable(targetResId);
            }
        }
       //这里获取找不到
        return context.getResources().getDrawable(resId);
    }
```
由于数据原因无法提供完整用户设备信息，crash都是系统4.4，大部分是x86，也有部分是armeabi-v7a，找不到的资源来自于v7包。

**Comment by YummyLau** [comment]
感谢这么晚还回复，堆栈是全的，我一直很疑惑。
另外，今天把源码重新看了一遍，因为线上app功能比较多比较复杂，换肤的时候有点卡顿。源码遍历了所有实现换肤接口的view并调用applySkin，这些ui操作一旦太多就会卡顿。目前是否有优化的手段。

2018年9月21日星期五，Pengfeng Wang <notifications@github.com> 写道：

**Comment by ximsfei** [comment]
你们现在接入的版本号是多少，其实最新的有优化，换肤只换当前页面。

**Comment by YummyLau** [comment]
嗯目前用的是2.2.3

**Comment by ximsfei** [comment]
这两个问题在新版本上应该修复了
