### ISSUE TITLE
StackOverflowError at SkinCompatDrawableUtils.canSafelyMutateDrawable

### ISSUE THREAD

**Issue by cooliceman** [ximsfei/Android-skin-support#246]
On android 4.4.4:
Fatal Exception: java.lang.StackOverflowError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
       at java.lang.StringBuilder.append(StringBuilder.java:216)
       at java.lang.Class.getConstructorOrMethod(Class.java:472)
       at java.lang.Class.getDeclaredMethod(Class.java:640)
       at skin.support.utils.SkinCompatVersionUtils.getV4WrappedDrawableWrappedDrawable(SourceFile:48)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
.....      
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableUtils.canSafelyMutateDrawable(SourceFile:62)
       at skin.support.content.res.SkinCompatDrawableManager.tintDrawable(SourceFile:251)
       at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SourceFile:191)
       at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SourceFile:174)
       at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SourceFile:187)
       at skin.support.content.res.SkinCompatResources.getDrawableCompat(SourceFile:252)
       at skin.support.widget.SkinCompatCompoundButtonHelper.applySkin(SourceFile:60)
       at skin.support.widget.SkinCompatCompoundButtonHelper.loadFromAttributes(SourceFile:48)
       at skin.support.widget.SkinCompatCheckBox.(SourceFile:30)
       at skin.support.widget.SkinCompatCheckBox.(SourceFile:24)
       at skin.support.app.SkinCompatViewInflater.createViewFromFV(SourceFile:164)
       at skin.support.app.SkinCompatViewInflater.createView(SourceFile:91)
       at skin.support.app.SkinCompatDelegate.createView(SourceFile:63)
       at skin.support.app.SkinCompatDelegate.onCreateView(SourceFile:37)
       at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(SourceFile:55)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:169)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:472)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.preference.PreferenceGroupAdapter.onCreateViewHolder(SourceFile:369)
       at android.support.v7.preference.PreferenceGroupAdapter.onCreateViewHolder(SourceFile:45)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(SourceFile:6794)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:5975)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5858)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5854)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile:2230)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1557)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:612)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3924)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3641)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile:4194)

I'm using skin.support:skin-support:3.1.1
I compared the code with the latest code and found that you've added canSafelyMutateDrawable(SkinCompatVersionUtils.getV7DrawableWrapperWrappedDrawable(drawable)) in the latest code.
If I don't want to upgrade to 4.x, what should I do, is it possible that you release version 3.1.2?

**Comment by cooliceman** [comment]
I've solved the problem,
We should keep the classes and methods that are used by reflection.
so it's better to add these lines in library's proguard file
`
-keep class android.support.v4.graphics.drawable.WrappedDrawable { *; }
-keep class android.support.v4.graphics.drawable.DrawableWrapper { *;}
-keep class android.support.v7.graphics.drawable.DrawableWrapper { *; }
`
