### ISSUE TITLE
skinListChoiceIndicatorSingle don't work on 4.x device when use vector drawable

### ISSUE THREAD

**Issue by cooliceman** [ximsfei/Android-skin-support#247]
```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/skin_btn_radio_checked_light.xml from drawable resource ID #0x7f08018e
     at android.content.res.Resources.loadDrawable(Resources.java:1958)
     at android.content.res.Resources.getDrawable(Resources.java:660)
     at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:173)
     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
     at android.content.res.Resources.loadDrawable(Resources.java:1955)
 	... 74 more
 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
     at android.content.res.Resources.loadDrawable(Resources.java:1955)
 	... 79 more
 android.content.res.Resources$NotFoundException: File res/drawable/skin_btn_radio_light.xml from drawable resource ID #0x7f08018f
    at android.content.res.Resources.loadDrawable(Resources.java:1958)
    at android.content.res.Resources.getDrawable(Resources.java:660)
    at skin.support.content.res.SkinCompatResources.getSkinDrawable(SkinCompatResources.java:177)
    at skin.support.content.res.SkinCompatResources.getDrawable(SkinCompatResources.java:248)
    at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:186)
    at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
    at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
    at skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
    at skin.support.widget.SkinCompatTextHelperV17.applyCompoundDrawablesRelativeResource(SkinCompatTextHelperV17.java:62)
    at skin.support.widget.SkinCompatTextHelper.applySkin(SkinCompatTextHelper.java:187)
    at skin.support.widget.SkinCompatTextHelper.loadFromAttributes(SkinCompatTextHelper.java:85)
    at skin.support.widget.SkinCompatTextHelperV17.loadFromAttributes(SkinCompatTextHelperV17.java:44)
    at skin.support.widget.SkinCompatCheckedTextView.<init>(SkinCompatCheckedTextView.java:41)
    at skin.support.widget.SkinCompatCheckedTextView.<init>(SkinCompatCheckedTextView.java:33)
    at skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:173)
    at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
    at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
    at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
    at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:168)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
```
skin_btn_radio_light.xml

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/skin_btn_radio_checked_light" android:state_checked="true" />
    <item android:drawable="@drawable/skin_btn_radio_unchecked_light" />
</selector>
```

skin_btn_radio_checked_light
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0">
    <path
        android:fillColor="#FF000000"
        android:pathData="M12,7c-2.76,0 -5,2.24 -5,5s2.24,5 5,5 5,-2.24 5,-5 -2.24,-5 -5,-5zM12,2C6.48,2 2,6.48 2,12s4.48,10 10,10 10,-4.48 10,-10S17.52,2 12,2zM12,20c-4.42,0 -8,-3.58 -8,-8s3.58,-8 8,-8 8,3.58 8,8 -3.58,8 -8,8z" />
</vector>
```

skin-support version:3.1.1
device os version:4.x

**Comment by ximsfei** [comment]
`AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);`

**Comment by cooliceman** [comment]
@ximsfei Thanks for your reply, I've solved the problem, it's not related to vector, but related to proguard.
We should keep the classes and methods that are used by reflection.
so it's better to add these lines in library's proguard file
`-keep class android.support.v4.graphics.drawable.WrappedDrawable { *; }
-keep class android.support.v4.graphics.drawable.DrawableWrapper { *;}
-keep class android.support.v7.graphics.drawable.DrawableWrapper { *; }`
