### ISSUE TITLE
预览失败  View.isInEditMode() Could not initialize class skin.support.content.res.SkinCompatUserThemeManager

### ISSUE THREAD

**Issue by scsfwgy** [ximsfei/Android-skin-support#258]
@ximsfei 

`java.lang.NoClassDefFoundError: Could not initialize class skin.support.content.res.SkinCompatUserThemeManager
	at skin.support.content.res.SkinCompatResources.getSkinDrawable(SkinCompatResources.java:156)
	at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:214)
	at skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
	at skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
	at skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
	at com.tophold.xcfd.ui.widget.skin.widget.SkinViewPager.<init>(SkinViewPager.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:299)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:385)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:509)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$4(RenderTask.java:638)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by scsfwgy** [comment]
`java.lang.NoClassDefFoundError: Could not initialize class skin.support.content.res.SkinCompatUserThemeManager`

**Comment by ximsfei** [comment]
已修复
