### ISSUE TITLE
show PopupMenu时会捕获到异常

### ISSUE THREAD

**Issue by zivids** [ximsfei/Android-skin-support#264]
drawable/abc_list_divider_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int)

java.lang.RuntimeException
        at android.content.res.Resources.getDrawable(Resources.java:746)
        at skin.support.content.res.SkinCompatResources.getSkinDrawable(SkinCompatResources.java:180)
        at skin.support.content.res.SkinCompatResources.getDrawable(SkinCompatResources.java:248)
        at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:186)
        at skin.support.content.res.SkinCompatDrawableManager.getDrawable(SkinCompatDrawableManager.java:174)
        at skin.support.content.res.SkinCompatResources.getSkinDrawableCompat(SkinCompatResources.java:187)
        at skin.support.content.res.SkinCompatResources.getDrawableCompat(SkinCompatResources.java:252)
        at skin.support.widget.SkinCompatBackgroundHelper.applySkin(SkinCompatBackgroundHelper.java:49)
        at skin.support.widget.SkinCompatBackgroundHelper.loadFromAttributes(SkinCompatBackgroundHelper.java:35)
        at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:27)
        at skin.support.widget.SkinCompatImageView.<init>(SkinCompatImageView.java:21)
        at skin.support.app.SkinCompatViewInflater.createViewFromFV(SkinCompatViewInflater.java:149)
        at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:91)
        at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:63)
        at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:37)
        at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:94)
        at android.support.v7.widget.DropDownListView.measureHeightOfChildrenCompat(DropDownListView.java:321)
        at android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.measureHeightOfChildrenCompat(MenuPopupWindow.java:129)
        at android.support.v7.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1301)
        at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:647)
        at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:201)
        at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:208)
        at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290)
        at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:177)
        at android.support.v7.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:143)
        at android.support.v7.widget.PopupMenu.show(PopupMenu.java:238)

**Comment by Lrony** [comment]
我也有遇到这个问题，但是不影响APP运行。
等作者帮忙解答～
