### ISSUE TITLE
java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by weiguet** [ximsfei/Android-skin-support#277]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at skin.support.app.SkinCompatDelegate.applySkin(SkinCompatDelegate.java:104) (#pluginId:host#)
	at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkinForce(SkinActivityLifecycle.java:214) (#pluginId:host#)
	at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkin(SkinActivityLifecycle.java:191) (#pluginId:host#)
	at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:40) (#pluginId:host#)
	at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:29) (#pluginId:host#)
	at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:402) (#pluginId:host#)
	at skin.support.c$a.onPostExecute(SkinCompatManager.java:355)
	at android.os.AsyncTask.finish(AsyncTask.java:696)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by androidsihai1** [comment]
I have the same question,who can help me ?

**Comment by imyetse** [comment]
dont addview in applyskin() method
