### ISSUE TITLE
Resources NotFoundException，ImageView设置src为selector后的切换报错

### ISSUE THREAD

**Issue by AndyGu** [ximsfei/Android-skin-support#278]
当ImageView设置的src为drawable，drawable为selector时，例：
<ImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/img_selector" />

<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@mipmap/img_selected"  android:state_selected="true"/>
    <item android:drawable="@mipmap/img_selected" android:state_pressed="true"/>
    <item android:drawable="@mipmap/img_normal" android:state_pressed="false" android:state_selected="false"/>
</selector>

切换日夜间时会报错，报错内容为查找不到night对应的resourceId

Caused by: android.view.InflateException: Binary XML file line #1050: Error inflating class ImageView
    Caused by: android.content.res.Resources$NotFoundException: Drawable com.bard.vgtime:drawable/img_selector_night with resource ID #0x7f080116
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/img_selector_night.xml from drawable resource ID #0x7f080116
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:898)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:903)
        at android.content.res.Resources.getDrawable(Resources.java:842)
        at android.content.res.Resources.getDrawable(Resources.java:817)
        at ha.h.b(SkinCompatVectorResources.java:81)
        at ha.h.a(SkinCompatVectorResources.java:89)
        at hh.l.a(SkinCompatImageHelper.java:56)
        at hh.l.a(SkinCompatImageHelper.java:35)
        at hh.m.<init>(SkinCompatImageView.java:30)
        at hh.m.<init>(SkinCompatImageView.java:21)
        at skin.support.app.b.b(SkinAppCompatViewInflater.java:81)
        at skin.support.app.b.a(SkinAppCompatViewInflater.java:51)
        at skin.support.app.e.c(SkinCompatViewInflater.java:77)
        at skin.support.app.e.a(SkinCompatViewInflater.java:46)
        at skin.support.app.d.b(SkinCompatDelegate.java:56)
        at skin.support.app.d.a(SkinCompatDelegate.java:31)
        at ad.j$a.onCreateView(LayoutInflaterCompat.java:55)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.bard.vgtime.base.fragment.a.onCreateView(BaseFragment.java:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2544)
        at androidx.fragment.app.h.a(FragmentManagerImpl.java:884)
        at androidx.fragment.app.h.j(FragmentManagerImpl.java:1235)
        at androidx.fragment.app.h.a(FragmentManagerImpl.java:1301)
        at androidx.fragment.app.a.m(BackStackRecord.java:710)
        at androidx.fragment.app.h.b(FragmentManagerImpl.java:2071)
        at androidx.fragment.app.h.a(FragmentManagerImpl.java:1861)
        at androidx.fragment.app.h.b(FragmentManagerImpl.java:1816)
        at androidx.fragment.app.h.b(FragmentManagerImpl.java:1693)
        at androidx.fragment.app.a.l(BackStackRecord.java:560)
        at androidx.fragment.app.k.finishUpdate(FragmentPagerAdapter.java:148)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:623)
        at com.bard.vgtime.activitys.MainActivity$3.onTabSelected(MainActivity.java:430)
        at com.google.android.material.tabs.TabLayout.dispatchTabSelected(TabLayout.java:1608)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1601)
2019-04-28 12:56:16.435 15656-15656/com.bard.vgtime E/AndroidRuntime:     at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1569)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:1874)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2059)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27801)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.view.InflateException: Class not found x
        at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:226)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:143)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1359)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1318)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:879)
        	... 64 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "x" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.bard.vgtime-AE_OckDfZWI0ujHAVN6WjQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.bard.vgtime-AE_OckDfZWI0ujHAVN6WjQ==/lib/arm, /data/app/com.bard.vgtime-AE_OckDfZWI0ujHAVN6WjQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:207)
        	... 68 more

**Comment by AndyGu** [comment]
selector 和ImageView没贴出来，补齐如下
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@mipmap/img_selected" android:state_selected="true"/>
    <item android:drawable="@mipmap/img_selected" android:state_pressed="true"/>
    <item android:drawable="@mipmap/img_normal" android:state_pressed="false" android:state_selected="false"/>
</selector>



<ImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/img_selector" />

**Comment by AndyGu** [comment]
ImageView和selector未发出来，补齐如下 
`<ImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/img_selector" />`


`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@mipmap/img_selected" android:state_selected="true"/>
    <item android:drawable="@mipmap/img_selected" android:state_pressed="true"/>
    <item android:drawable="@mipmap/img_normal" android:state_pressed="false" android:state_selected="false"/>
</selector>`

**Comment by tianyu704** [comment]
img_selector_night.xml你定义了么？

**Comment by AndyGu** [comment]
定义了的，我用demo使用selector是不会报错的，所以在想是什么原因，是不是可能和代码混淆、MultiDexApplication分包、日夜间初始化有关，报错提示的是NotFoundException: File res/drawable/img_selector_night.xml from drawable resource ID #0x7f080116，为什么是在res文件夹下而不是在res-night文件夹下寻找，还在查找原因 =。=

**Comment by Elaine666** [comment]
你是动态代码加载的还是直接在布局文件中使用？

**Comment by AndyGu** [comment]
@tianyu704 @Elaine666 原因找到了，是代码设置的原因，漏加了		AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);，并且在代码中加了动态根据日间间模式设置图片的内容，现在图片都能正常替换了。
有个关于textview的问题，就是demo中包括FAQ里都提示用textAppearance实现textColor的换肤操作，但是我发现在demo中的style中的background无法生效，是否只有textColor可以通过这种方法换肤
