### ISSUE TITLE
ColorStateList Error

### ISSUE THREAD

**Issue by DragonTotem** [ximsfei/Android-skin-support#318]
My App starts with the following error:

W/Resources: ColorStateList xxxe:color/mtrl_tabs_legacy_text_color_selector has unresolved theme attributes! Consider using Resources.getColorStateList(int, Theme) or Context.getColorStateList(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getColorStateList(Resources.java:1119)
        at skin.support.content.res.SkinCompatResources.getSkinColorStateList(SkinCompatResources.java:166)
        at skin.support.content.res.SkinCompatResources.getColorStateList(SkinCompatResources.java:230)
        at skin.support.widget.SkinCompatTextHelper.applyTextColorResource(SkinCompatTextHelper.java:121)
        at skin.support.widget.SkinCompatTextHelper.applySkin(SkinCompatTextHelper.java:183)
        at skin.support.widget.SkinCompatTextView.applySkin(SkinCompatTextView.java:77)
        at skin.support.app.SkinCompatDelegate.applySkin(SkinCompatDelegate.java:81)
        at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkinForce(SkinActivityLifecycle.java:190)
        at skin.support.app.SkinActivityLifecycle$LazySkinObserver.updateSkin(SkinActivityLifecycle.java:168)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:41)
        at skin.support.observe.SkinObservable.notifyUpdateSkin(SkinObservable.java:30)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:414)
        at skin.support.SkinCompatManager$SkinLoadTask.onPostExecute(SkinCompatManager.java:364)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

I hope it can be repair.  Modify {@link skin.support.content.res#getSkinColorStateList}  as follows:

  private ColorStateList getSkinColorStateList(Context context, int resId) {
        if (!SkinCompatUserThemeManager.get().isColorEmpty()) {
            ColorStateList colorStateList = SkinCompatUserThemeManager.get().getColorStateList(resId);
            if (colorStateList != null) {
                return colorStateList;
            }
        }
        if (mStrategy != null) {
            ColorStateList colorStateList = mStrategy.getColorStateList(context, mSkinName, resId);
            if (colorStateList != null) {
                return colorStateList;
            }
        }
        if (!isDefaultSkin) {
            int targetResId = getTargetResId(context, resId);
            if (targetResId != 0) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    return mResources.getColorStateList(targetResId, context.getTheme());
                } else {
                    return mResources.getColorStateList(resId);
                }
            }
        }
        return ContextCompat.getColorStateList(context, resId);
    }

**Comment by ximsfei** [comment]
已修复
