### ISSUE TITLE
OPPO R17手机长按输入框复制粘贴时候报错

### ISSUE THREAD

**Issue by ldpadelin** [ximsfei/Android-skin-support#339]

**Comment by ldpadelin** [comment]
Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class ImageButton
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0xc0104f0 a=-1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
        at android.widget.ImageView.<init>(ImageView.java:211)
        at android.widget.ImageButton.<init>(ImageButton.java:86)
        at android.widget.ImageButton.<init>(ImageButton.java:82)
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:73)
        at skin.support.widget.SkinCompatImageButton.<init>(SkinCompatImageButton.java:26)
        at skin.support.widget.SkinCompatImageButton.<init>(SkinCompatImageButton.java:22)
        at skin.support.app.SkinAppCompatViewInflater.createViewFromFV(SkinAppCompatViewInflater.java:93)
        at skin.support.app.SkinAppCompatViewInflater.createView(SkinAppCompatViewInflater.java:51)
        at skin.support.app.SkinCompatViewInflater.createViewFromInflater(SkinCompatViewInflater.java:77)
        at skin.support.app.SkinCompatViewInflater.createView(SkinCompatViewInflater.java:46)
        at skin.support.app.SkinCompatDelegate.createView(SkinCompatDelegate.java:70)
        at skin.support.app.SkinCompatDelegate.onCreateView(SkinCompatDelegate.java:31)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:742)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.widget.ColorFloatingToolbarPopup.createOverflowButton(ColorFloatingToolbarPopup.java:722)
        at com.android.internal.widget.ColorFloatingToolbarPopup.<init>(ColorFloatingToolbarPopup.java:208)
        at com.android.internal.widget.FloatingToolbar.<init>(FloatingToolbar.java:153)
        at com.android.internal.policy.DecorView.createFloatingActionMode(DecorView.java:2019)
        at com.android.internal.policy.DecorView.createActionMode(DecorView.java:1868)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1002)
        at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:959)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:928)
        at android.view.View.startActionMode(View.java:6590)
        at android.widget.Editor.startInsertionActionMode(Editor.java:2035)
        at android.widget.TextView.onTouchEvent(TextView.java:9782)
        at android.view.View.dispatchTouchEvent(View.java:11916)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
