### ISSUE TITLE
项目中有高德导航，跳到最新导航界面过程种报错

### ISSUE THREAD

**Issue by Tonny2011** [ximsfei/Android-skin-support#340]
Process: com.zxd.newproject, PID: 19557
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zxd.newproject/com.amap.api.navi.AmapRouteActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2858)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6530)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
        at android.app.DialogFragment.onActivityCreated(DialogFragment.java:482)
        at android.app.Fragment.performActivityCreated(Fragment.java:2517)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreate(Activity.java:7042)
        at android.app.Activity.performCreate(Activity.java:7027)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2858) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6530) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Tonny2011** [comment]
引用内换肤

**Comment by Tonny2011** [comment]
4.0的版本

**Comment by ximsfei** [comment]
如果项目中存在三方不需要换肤的activity，可以使用[setSkinAllActivityEnable](https://github.com/ximsfei/Android-skin-support/blob/d3f9c8d7076fa1764705ac563d9b5c5395b17673/androidx/skin-support/src/main/java/skin/support/SkinCompatManager.java#L263)，开启部分Activity换肤
