### ISSUE TITLE
debug模式下没问题 release下就会找不到资源

### ISSUE THREAD

**Issue by 995085226** [ximsfei/Android-skin-support#348]
android.content.res.Resources$NotFoundException: Drawable com.demomaker.mchat:drawable/tab_contact_selector_night with resource ID #0x7f08011a
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3004)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3082)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7069)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.demomaker.mchat:drawable/tab_contact_selector_night with resource ID #0x7f08011a
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/tab_contact_selector_night.xml from drawable resource ID #0x7f0801

是需要配置混淆么

**Comment by Zfashion** [comment]
I had the same problem

**Comment by 995085226** [comment]
原因是打包的时候gradle配置去除无用资源 把这个配置去掉就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZFashion"; 
发送时间: 2020年5月18日(星期一) 下午5:34
收件人: "ximsfei/Android-skin-support";
抄送: "995085226"<995085226@qq.com>;"Author";
主题: Re: [ximsfei/Android-skin-support] debug模式下没问题 release下就会找不到资源 (#348)





 
I had the same problem
 
&mdash;
