### ISSUE TITLE
crash平台监听到的报错：java.lang.IllegalStateException: Could not execute method for android:onClick

### ISSUE THREAD

**Issue by tianyu704** [ximsfei/Android-skin-support#363]
java.lang.IllegalStateException: Could not execute method for android:onClick
    at skin.support.app.SkinCompatViewInflater$DeclaredOnClickListener.onClick(SkinCompatViewInflater.java:4)
    at android.view.View.performClick(View.java:6614)
    at android.view.View.performClickInternal(View.java:6587)
    at android.view.View.access$3100(View.java:787)
    at android.view.View$PerformClick.run(View.java:26122)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6831)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)

**Comment by ximsfei** [comment]
@tianyu704  这个异常，可能是点击事件crash，先check一下代码？
