### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by GXSZone** [ximsfei/Android-skin-support#412]
崩溃信息:

**No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in /data/app/com.aa.bb-RxDsGCclYbWDy2onEiaiYQ==/base.apk!classes2.dex)**

类名:SkinCompatDrawableManager.java

方法:<clinit>

行数:108

类型:java.lang.NoSuchFieldError

时间:2020-10-08_19:40

设备名称:PCCM00

设备厂商:OPPO

系统版本:Android 10-29

CPU-ABI:arm64-v8a

versionCode:1

versionName:1.0

全部信息:
```
java.lang.NoSuchFieldError: No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in /data/app/com.aa.bb-RxDsGCclYbWDy2onEiaiYQ==/base.apk!classes2.dex)
	at skin.support.content.res.SkinCompatDrawableManager.<clinit>(SkinCompatDrawableManager.java:108)
	at skin.support.content.res.SkinCompatDrawableManager.get(SkinCompatDrawableManager.java:60)
	at skin.support.content.res.SkinCompatVectorResources.clear(SkinCompatVectorResources.java:30)
	at skin.support.content.res.SkinCompatResources.setupSkin(SkinCompatResources.java:76)
	at skin.support.load.SkinBuildInLoader.loadSkinInBackground(SkinBuildInLoader.java:14)
	at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:394)
	at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:364)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)


```

**Comment by GXSZone** [comment]
implementation 'androidx.appcompat:appcompat:1.3.0-alpha02' 换成1.2.0 就好了  或者改依赖

**Comment by liusanhong** [comment]
b

> ```
> implementation 'androidx.appcompat:appcompat:1.3.0-alpha02' 换成1.2.0 就好了  或者改依赖
> ```

不行啊，还是有

**Comment by xiaoxing1992** [comment]
> b
> 
> > ```
> > implementation 'androidx.appcompat:appcompat:1.3.0-alpha02' 换成1.2.0 就好了  或者改依赖
> > ```
> 
> 不行啊，还是有

你的解决了吗  求方法

**Comment by wtyn** [comment]
> ```
> implementation 'androidx.appcompat:appcompat:1.3.0-alpha02' 换成1.2.0 就好了  或者改依赖
> ```

的确改成这个就可以了。但感觉这个库已经不维护了，以后还是有问题
