### ISSUE TITLE
切换crash

### ISSUE THREAD

**Issue by huang72590** [ximsfei/Android-skin-support#438]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchFieldError: No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in /data/app/org.vidonme.box.phone-9vAjX3TAtNNSJ7Zni6geag==/base.apk:classes2.dex)
	at skin.support.content.res.SkinCompatDrawableManager.<clinit>(SkinCompatDrawableManager.java:108)
	at skin.support.content.res.SkinCompatDrawableManager.get(SkinCompatDrawableManager.java:60)
	at skin.support.content.res.SkinCompatVectorResources.clear(SkinCompatVectorResources.java:30)
	at skin.support.content.res.SkinCompatResources.setupSkin(SkinCompatResources.java:76)
	at skin.support.load.SkinBuildInLoader.loadSkinInBackground(SkinBuildInLoader.java:14)
	at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:394)
	at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:364)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by KaJunChan** [comment]
我也是这样,有办法解决吗

**Comment by AndroidLMY** [comment]
我也遇到该问题 请问解决了吗

**Comment by huang72590** [comment]
'androidx.appcompat 这个降级到1.3.0一下就行

**Comment by zengchen1** [comment]
'androidx.appcompat 这个降级到1.3.0  我试了不行  1.2.0才可以运行

**Comment by hardyio** [comment]
> 'androidx.appcompat 这个降级到1.3.0 我试了不行 1.2.0才可以运行

感谢
