### ISSUE TITLE
颜色切换报错

### ISSUE THREAD

**Issue by lixiongh-hou** [ximsfei/Android-skin-support#461]
作者你好，在我切换颜色时候出现了这个错误
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.viva.pokemon, PID: 23253
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NoSuchFieldError: No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in /data/app/com.viva.pokemon-i_01VB4aBjve-QdDUTjfKw==/base.apk!classes2.dex)
        at skin.support.content.res.SkinCompatDrawableManager.<clinit>(SkinCompatDrawableManager.java:108)
        at skin.support.content.res.SkinCompatDrawableManager.get(SkinCompatDrawableManager.java:60)
        at skin.support.content.res.SkinCompatVectorResources.clear(SkinCompatVectorResources.java:30)
        at skin.support.content.res.SkinCompatResources.setupSkin(SkinCompatResources.java:76)
        at skin.support.load.SkinBuildInLoader.loadSkinInBackground(SkinBuildInLoader.java:14)
        at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:394)
        at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:364)`
是那个地方配置错了吗，我使用的是values-night方式，在触发这个代码时候闪退
`SkinCompatManager.getInstance().loadSkin("night", SkinCompatManager.SKIN_LOADER_STRATEGY_BUILD_IN)`

**Comment by tangqing1992** [comment]
大神，出现同样的问题，怎样解决？

**Comment by Alembertcn** [comment]
+1

**Comment by Clark-caipeiyuan** [comment]
allprojects {

configurations.all {
    resolutionStrategy {
        force 'androidx.appcompat:appcompat:1.2.0'
    }
}
}
project.gradle 里面强制限定appcompat的版本
