### ISSUE TITLE
高版本安卓的已经无法使用

### ISSUE THREAD

**Issue by chejfj** [ximsfei/Android-skin-support#485]
2024-04-21 17:22:57.982 22608-22644/com.qiang.skintest E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.qiang.skintest, PID: 22608
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:426)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:930)
     Caused by: java.lang.NoSuchFieldError: No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in /data/app/~~JB9zF-rSewWcTfnLzP086w==/com.qiang.skintest-X9JjHNcyDY5-TygtzQI0fw==/base.apk!classes2.dex)
        at skin.support.content.res.SkinCompatDrawableManager.<clinit>(SkinCompatDrawableManager.java:108)
        at skin.support.content.res.SkinCompatDrawableManager.get(SkinCompatDrawableManager.java:60)
        at skin.support.content.res.SkinCompatVectorResources.clear(SkinCompatVectorResources.java:30)
        at skin.support.content.res.SkinCompatResources.setupSkin(SkinCompatResources.java:76)
        at skin.support.load.SkinBuildInLoader.loadSkinInBackground(SkinBuildInLoader.java:14)
        at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:394)
        at skin.support.SkinCompatManager$SkinLoadTask.doInBackground(SkinCompatManager.java:364)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:930)

**Comment by ragecaty** [comment]
什么安卓版本？

**Comment by jisx** [comment]
这个报错很像使用了插件化框架，插件打包后，在壳中运行，但资源没对齐的异常

**Comment by everyline** [comment]
appcompat = "1.6.1"
material = "1.10.0"   无法使用 这个库

**Comment by jarkeet** [comment]
好像是appcompat版本问题，120可以130就不行了，资源找不到，作者用的110编译的

**Comment by Se7enLee** [comment]
> 好像是appcompat版本问题，120可以130就不行了，资源找不到，作者用的110编译的
我用的 1.6.1  和 1.9.0没问题
